### ISSUE TITLE
run_number and description

### ISSUE THREAD

**Issue by mle2718** [kimberly-bastille/groundfishRecDST_Shiny#22]
Plot run number and keep description of the model in the table? this forces people to find the run number. which is not great

or allow people to put in anything for the run_name and run the risk of the figures looking awful.

**Comment by mle2718** [comment]
I think we have to go with this

> or allow people to put in anything for the run_name and run the risk of the figures looking awful.

**Comment by kimberly-bastille** [comment]
Run Name currently has no hard coded limits. Only a suggestion to make in short. I think the figure is going to be ugly after a while and we are currently making no code efforts to prevent that. 

The figure will be cleaned and presented at the January Meeting in the cleanest format we can build but that will happen outside of the app.
