### ISSUE TITLE
! `run_number` must be size 150 or 1, not 90.

### ISSUE THREAD

**Issue by mle2718** [kimberly-bastille/groundfishRecDST_Shiny#30]
I'm getting an error message here when I have a just the 2draws csv in my output folder.  I think it's because there are 120 rows of "data" and then 30 rows of regulations. I do not know how to solve this easily.

https://github.com/kimberly-bastille/groundfishRecDST_Shiny/blob/049237508887803a990bf199c13522934e8b2006/app.R#L245

**Comment by kimberly-bastille** [comment]
Yes so the `each= 90` is the number of rows for each output if they are run with mrip_index 1:4. 2draws was run with mrip_index 1:8  so will need to increase `each = 150`. 

this will need to be set to  `each = 6030` when pushed to cloud to run all mrip_index 1:400, meaning all 100 draws.

**Comment by mle2718** [comment]
okay. so nothing to do for now since all the runs can be guaranteed to have 100 replicates.

**Comment by kimberly-bastille** [comment]
Yes it is only down scaled for the local dev period.
